server:
  port: 8081
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/mydb01?serverTimezone=UTC
      username: root
      password: 413026
  hikari:
    maximum-pool-size: 20
    minimum-idle: 10
mybatis:
  type-aliases-package: com.leyou.demo.userservice.instance
  configuration:classpath: mybatis/mybatis-config.xml
  mapper-locations: classpath:mappers/*.xml